import chalk from 'chalk';
import type { ReviewResult, Risk, RiskSeverity } from '../types/index.js';

const SEVERITY_COLORS: Record<RiskSeverity, (text: string) => string> = {
  critical: chalk.bgRed.white.bold,
  high: chalk.red.bold,
  medium: chalk.yellow,
  low: chalk.blue,
};

const SEVERITY_EMOJI: Record<RiskSeverity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
};

const CATEGORY_EMOJI: Record<string, string> = {
  performance: '⚡',
  security: '🔒',
  maintainability: '🔧',
  'best-practice': '✨',
  style: '🎨',
};

export function formatForTerminal(result: ReviewResult): string {
  const lines: string[] = [];

  // Header
  lines.push('');
  lines.push(chalk.bold.cyan('═══════════════════════════════════════════════════════'));
  lines.push(chalk.bold.cyan('  PRISM REVIEW'));
  lines.push(chalk.bold.cyan('═══════════════════════════════════════════════════════'));
  lines.push('');

  // PR Info
  lines.push(chalk.bold(`PR #${result.pr.number}: ${result.pr.title}`));
  lines.push(chalk.gray(`${result.pr.headBranch} → ${result.pr.baseBranch}`));
  lines.push(chalk.gray(`${result.pr.changedFiles} files • +${result.pr.additions} -${result.pr.deletions}`));
  lines.push('');

  // Summary
  lines.push(chalk.bold.white('📋 Summary'));
  lines.push(chalk.gray('─'.repeat(55)));
  lines.push(result.summary);
  lines.push('');

  // Risks
  if (result.risks.length > 0) {
    lines.push(chalk.bold.white('⚠️  Risk Assessment'));
    lines.push(chalk.gray('─'.repeat(55)));
    for (const risk of result.risks) {
      const colorFn = SEVERITY_COLORS[risk.severity];
      const emoji = SEVERITY_EMOJI[risk.severity];
      lines.push(`${emoji} ${colorFn(risk.severity.toUpperCase())} ${chalk.dim(risk.file)}`);
      lines.push(`   ${risk.description}`);
      if (risk.suggestion) {
        lines.push(chalk.green(`   → ${risk.suggestion}`));
      }
      lines.push('');
    }
  } else {
    lines.push(chalk.green('✓ No significant risks identified'));
    lines.push('');
  }

  // Suggestions
  if (result.suggestions.length > 0) {
    lines.push(chalk.bold.white('💡 Suggestions'));
    lines.push(chalk.gray('─'.repeat(55)));
    for (const suggestion of result.suggestions) {
      const emoji = CATEGORY_EMOJI[suggestion.category] || '•';
      lines.push(`${emoji} ${chalk.dim(suggestion.file)} ${chalk.gray(`[${suggestion.category}]`)}`);
      lines.push(`   ${suggestion.description}`);
      if (suggestion.code) {
        lines.push(chalk.gray(`   \`${suggestion.code}\``));
      }
      lines.push('');
    }
  }

  // Test Gaps
  if (result.testGaps.length > 0) {
    lines.push(chalk.bold.white('🧪 Test Coverage Gaps'));
    lines.push(chalk.gray('─'.repeat(55)));
    for (const gap of result.testGaps) {
      const priorityColor = gap.priority === 'high' ? chalk.red : gap.priority === 'medium' ? chalk.yellow : chalk.blue;
      lines.push(`${priorityColor('●')} ${chalk.dim(gap.file)}`);
      lines.push(`   ${gap.description}`);
      if (gap.suggestedTests.length > 0) {
        lines.push(chalk.gray('   Suggested tests:'));
        for (const test of gap.suggestedTests) {
          lines.push(chalk.gray(`     • ${test}`));
        }
      }
      lines.push('');
    }
  }

  // Footer
  lines.push(chalk.gray('─'.repeat(55)));
  lines.push(chalk.dim(`Generated by Prism Review • ${result.modelUsed}`));
  lines.push(chalk.dim(result.generatedAt.toISOString()));
  lines.push('');

  return lines.join('\n');
}

export function formatForGitHub(result: ReviewResult): string {
  const lines: string[] = [];

  lines.push('<!-- prism-review -->');
  lines.push('## 🔍 Prism Review');
  lines.push('');

  // Summary
  lines.push('### 📋 Summary');
  lines.push(result.summary);
  lines.push('');

  // Stats
  lines.push(`> **${result.pr.changedFiles}** files changed • **+${result.pr.additions}** additions • **-${result.pr.deletions}** deletions`);
  lines.push('');

  // Risks
  if (result.risks.length > 0) {
    lines.push('### ⚠️ Risk Assessment');
    lines.push('');
    lines.push('| Severity | File | Issue | Suggestion |');
    lines.push('|:--------:|------|-------|------------|');
    for (const risk of result.risks) {
      const severityBadge = getSeverityBadge(risk.severity);
      const lineRef = risk.line ? `:${risk.line}` : '';
      lines.push(
        `| ${severityBadge} | \`${risk.file}${lineRef}\` | ${risk.description} | ${risk.suggestion || '-'} |`
      );
    }
    lines.push('');
  } else {
    lines.push('### ✅ No Significant Risks');
    lines.push('No critical issues found in this PR.');
    lines.push('');
  }

  // Suggestions
  if (result.suggestions.length > 0) {
    lines.push('### 💡 Suggestions');
    lines.push('');
    for (const suggestion of result.suggestions) {
      const emoji = CATEGORY_EMOJI[suggestion.category] || '•';
      const lineRef = suggestion.line ? `:${suggestion.line}` : '';
      lines.push(`- ${emoji} **\`${suggestion.file}${lineRef}\`** _(${suggestion.category})_`);
      lines.push(`  ${suggestion.description}`);
      if (suggestion.code) {
        lines.push(`  \`\`\`\n  ${suggestion.code}\n  \`\`\``);
      }
    }
    lines.push('');
  }

  // Test Gaps
  if (result.testGaps.length > 0) {
    lines.push('### 🧪 Test Coverage Gaps');
    lines.push('');
    for (const gap of result.testGaps) {
      const priorityIcon = gap.priority === 'high' ? '🔴' : gap.priority === 'medium' ? '🟡' : '🔵';
      lines.push(`<details><summary>${priorityIcon} <b>${gap.file}</b> - ${gap.description}</summary>`);
      lines.push('');
      lines.push('**Suggested tests:**');
      for (const test of gap.suggestedTests) {
        lines.push(`- [ ] ${test}`);
      }
      lines.push('');
      lines.push('</details>');
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push(`<sub>🔮 Generated by [Prism Review](https://github.com/jpdlr/prism-review) • ${result.modelUsed} • ${result.generatedAt.toISOString()}</sub>`);

  return lines.join('\n');
}

function getSeverityBadge(severity: RiskSeverity): string {
  switch (severity) {
    case 'critical':
      return '🔴 Critical';
    case 'high':
      return '🟠 High';
    case 'medium':
      return '🟡 Medium';
    case 'low':
      return '🔵 Low';
  }
}

export function formatAsJson(result: ReviewResult): string {
  return JSON.stringify(result, null, 2);
}
